### ISSUE TITLE
 Exception in thread "main" java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')         at me.ping.unfynel.Run.run(Run.java:41)         at me.ping.unfynel.PingBot.launch(PingBot.java:52)         at me.ping.unfynel.Main.main(Main.java:9)

### ISSUE THREAD

**Issue by blackowlzz** [theDesConnet/EvilMC#5]
I get this error when i do the slash commands for every crash command:  

` Exception in thread "main" java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')
        at me.ping.unfynel.Run.run(Run.java:41)
        at me.ping.unfynel.PingBot.launch(PingBot.java:52)
        at me.ping.unfynel.Main.main(Main.java:9)`

**Comment by theDesConnet** [comment]
what version of java is worth?

**Comment by thetoxic305** [comment]
I need help i can't send DesConnet#9393 friend request
