### ISSUE TITLE
issue on startup

### ISSUE THREAD

**Issue by Light1940** [theDesConnet/EvilMC#6]
/home/container/structure/language.js:23
        let textBuilder = this.languageFile.text[id];
                                                ^
TypeError: Cannot read properties of undefined (reading 'loadedLanguage')
    at Language.getText (/home/container/structure/language.js:23:49)
    at new Language (/home/container/structure/language.js:10:36)
    at new Client (/home/container/structure/client.js:49:25)
    at /home/container/bot.js:21:24
    at Object.<anonymous> (/home/container/bot.js:23:7)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
Node.js v18.16.0

**Comment by Light1940** [comment]
dm me please if i dont respond here  Light1940#7009

**Comment by theDesConnet** [comment]
please show me this parameter in config file
![изображение](https://github.com/theDesConnet/EvilMC/assets/31757032/eff1b2da-de75-4d4d-8446-ea1470546172)

**Comment by Light1940** [comment]
is this good? 
![image](https://github.com/theDesConnet/EvilMC/assets/134773127/3c57bae5-4c73-46a9-b7da-3193b087cc6d)

**Comment by theDesConnet** [comment]
bot has been updated to version 2.0
